services:
  sweapi:
    image: docker.io/jhon5456/swegrpc:latest
    ports:
      - "5678:5678"
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/jhon5456/swewebapp:latest
    depends_on:
      - sweapi
    ports:
      - "8081:8081"
    environment:
      - ENV=container
      - CONFIG_PATH=/app/config
  webapp-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: swewebapp-dev:latest
    depends_on:
      - sweapi
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      - ENV=container
      - CONFIG_PATH=/app/config
