// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package lib

import (
	"context"

	"github.com/jenujari/go-swe-api/proto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSweGrpcClient creates a new instance of MockSweGrpcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSweGrpcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSweGrpcClient {
	mock := &MockSweGrpcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSweGrpcClient is an autogenerated mock type for the SweGrpcClient type
type MockSweGrpcClient struct {
	mock.Mock
}

type MockSweGrpcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSweGrpcClient) EXPECT() *MockSweGrpcClient_Expecter {
	return &MockSweGrpcClient_Expecter{mock: &_m.Mock}
}

// FindConjunction provides a mock function for the type MockSweGrpcClient
func (_mock *MockSweGrpcClient) FindConjunction(ctx context.Context, start string, end string, planet1 string, planet2 string, orb int32, step float64) (*proto.ConjunctionResponse, error) {
	ret := _mock.Called(ctx, start, end, planet1, planet2, orb, step)

	if len(ret) == 0 {
		panic("no return value specified for FindConjunction")
	}

	var r0 *proto.ConjunctionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, int32, float64) (*proto.ConjunctionResponse, error)); ok {
		return returnFunc(ctx, start, end, planet1, planet2, orb, step)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, int32, float64) *proto.ConjunctionResponse); ok {
		r0 = returnFunc(ctx, start, end, planet1, planet2, orb, step)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ConjunctionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, int32, float64) error); ok {
		r1 = returnFunc(ctx, start, end, planet1, planet2, orb, step)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSweGrpcClient_FindConjunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindConjunction'
type MockSweGrpcClient_FindConjunction_Call struct {
	*mock.Call
}

// FindConjunction is a helper method to define mock.On call
//   - ctx context.Context
//   - start string
//   - end string
//   - planet1 string
//   - planet2 string
//   - orb int32
//   - step float64
func (_e *MockSweGrpcClient_Expecter) FindConjunction(ctx interface{}, start interface{}, end interface{}, planet1 interface{}, planet2 interface{}, orb interface{}, step interface{}) *MockSweGrpcClient_FindConjunction_Call {
	return &MockSweGrpcClient_FindConjunction_Call{Call: _e.mock.On("FindConjunction", ctx, start, end, planet1, planet2, orb, step)}
}

func (_c *MockSweGrpcClient_FindConjunction_Call) Run(run func(ctx context.Context, start string, end string, planet1 string, planet2 string, orb int32, step float64)) *MockSweGrpcClient_FindConjunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int32
		if args[5] != nil {
			arg5 = args[5].(int32)
		}
		var arg6 float64
		if args[6] != nil {
			arg6 = args[6].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockSweGrpcClient_FindConjunction_Call) Return(conjunctionResponse *proto.ConjunctionResponse, err error) *MockSweGrpcClient_FindConjunction_Call {
	_c.Call.Return(conjunctionResponse, err)
	return _c
}

func (_c *MockSweGrpcClient_FindConjunction_Call) RunAndReturn(run func(ctx context.Context, start string, end string, planet1 string, planet2 string, orb int32, step float64) (*proto.ConjunctionResponse, error)) *MockSweGrpcClient_FindConjunction_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalas provides a mock function for the type MockSweGrpcClient
func (_mock *MockSweGrpcClient) GetBalas(ctx context.Context, ts string) (*proto.BalasResponse, error) {
	ret := _mock.Called(ctx, ts)

	if len(ret) == 0 {
		panic("no return value specified for GetBalas")
	}

	var r0 *proto.BalasResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*proto.BalasResponse, error)); ok {
		return returnFunc(ctx, ts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *proto.BalasResponse); ok {
		r0 = returnFunc(ctx, ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.BalasResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSweGrpcClient_GetBalas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalas'
type MockSweGrpcClient_GetBalas_Call struct {
	*mock.Call
}

// GetBalas is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
func (_e *MockSweGrpcClient_Expecter) GetBalas(ctx interface{}, ts interface{}) *MockSweGrpcClient_GetBalas_Call {
	return &MockSweGrpcClient_GetBalas_Call{Call: _e.mock.On("GetBalas", ctx, ts)}
}

func (_c *MockSweGrpcClient_GetBalas_Call) Run(run func(ctx context.Context, ts string)) *MockSweGrpcClient_GetBalas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSweGrpcClient_GetBalas_Call) Return(balasResponse *proto.BalasResponse, err error) *MockSweGrpcClient_GetBalas_Call {
	_c.Call.Return(balasResponse, err)
	return _c
}

func (_c *MockSweGrpcClient_GetBalas_Call) RunAndReturn(run func(ctx context.Context, ts string) (*proto.BalasResponse, error)) *MockSweGrpcClient_GetBalas_Call {
	_c.Call.Return(run)
	return _c
}

// GetPos provides a mock function for the type MockSweGrpcClient
func (_mock *MockSweGrpcClient) GetPos(ctx context.Context, datetime string, planet string) (*proto.PosResponse, error) {
	ret := _mock.Called(ctx, datetime, planet)

	if len(ret) == 0 {
		panic("no return value specified for GetPos")
	}

	var r0 *proto.PosResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*proto.PosResponse, error)); ok {
		return returnFunc(ctx, datetime, planet)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *proto.PosResponse); ok {
		r0 = returnFunc(ctx, datetime, planet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.PosResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, datetime, planet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSweGrpcClient_GetPos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPos'
type MockSweGrpcClient_GetPos_Call struct {
	*mock.Call
}

// GetPos is a helper method to define mock.On call
//   - ctx context.Context
//   - datetime string
//   - planet string
func (_e *MockSweGrpcClient_Expecter) GetPos(ctx interface{}, datetime interface{}, planet interface{}) *MockSweGrpcClient_GetPos_Call {
	return &MockSweGrpcClient_GetPos_Call{Call: _e.mock.On("GetPos", ctx, datetime, planet)}
}

func (_c *MockSweGrpcClient_GetPos_Call) Run(run func(ctx context.Context, datetime string, planet string)) *MockSweGrpcClient_GetPos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSweGrpcClient_GetPos_Call) Return(posResponse *proto.PosResponse, err error) *MockSweGrpcClient_GetPos_Call {
	_c.Call.Return(posResponse, err)
	return _c
}

func (_c *MockSweGrpcClient_GetPos_Call) RunAndReturn(run func(ctx context.Context, datetime string, planet string) (*proto.PosResponse, error)) *MockSweGrpcClient_GetPos_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockSweGrpcClient
func (_mock *MockSweGrpcClient) Ping(ctx context.Context) (*proto.PingResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *proto.PingResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*proto.PingResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *proto.PingResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.PingResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSweGrpcClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockSweGrpcClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSweGrpcClient_Expecter) Ping(ctx interface{}) *MockSweGrpcClient_Ping_Call {
	return &MockSweGrpcClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockSweGrpcClient_Ping_Call) Run(run func(ctx context.Context)) *MockSweGrpcClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSweGrpcClient_Ping_Call) Return(pingResponse *proto.PingResponse, err error) *MockSweGrpcClient_Ping_Call {
	_c.Call.Return(pingResponse, err)
	return _c
}

func (_c *MockSweGrpcClient_Ping_Call) RunAndReturn(run func(ctx context.Context) (*proto.PingResponse, error)) *MockSweGrpcClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Tithy provides a mock function for the type MockSweGrpcClient
func (_mock *MockSweGrpcClient) Tithy(ctx context.Context, timestamp string) (*proto.TithyResponse, error) {
	ret := _mock.Called(ctx, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for Tithy")
	}

	var r0 *proto.TithyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*proto.TithyResponse, error)); ok {
		return returnFunc(ctx, timestamp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *proto.TithyResponse); ok {
		r0 = returnFunc(ctx, timestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TithyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, timestamp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSweGrpcClient_Tithy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tithy'
type MockSweGrpcClient_Tithy_Call struct {
	*mock.Call
}

// Tithy is a helper method to define mock.On call
//   - ctx context.Context
//   - timestamp string
func (_e *MockSweGrpcClient_Expecter) Tithy(ctx interface{}, timestamp interface{}) *MockSweGrpcClient_Tithy_Call {
	return &MockSweGrpcClient_Tithy_Call{Call: _e.mock.On("Tithy", ctx, timestamp)}
}

func (_c *MockSweGrpcClient_Tithy_Call) Run(run func(ctx context.Context, timestamp string)) *MockSweGrpcClient_Tithy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSweGrpcClient_Tithy_Call) Return(tithyResponse *proto.TithyResponse, err error) *MockSweGrpcClient_Tithy_Call {
	_c.Call.Return(tithyResponse, err)
	return _c
}

func (_c *MockSweGrpcClient_Tithy_Call) RunAndReturn(run func(ctx context.Context, timestamp string) (*proto.TithyResponse, error)) *MockSweGrpcClient_Tithy_Call {
	_c.Call.Return(run)
	return _c
}
