// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqls

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ExchangeType string

const (
	ExchangeTypeBSE ExchangeType = "BSE"
	ExchangeTypeNSE ExchangeType = "NSE"
)

func (e *ExchangeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExchangeType(s)
	case string:
		*e = ExchangeType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExchangeType: %T", src)
	}
	return nil
}

type NullExchangeType struct {
	ExchangeType ExchangeType `json:"exchange_type"`
	Valid        bool         `json:"valid"` // Valid is true if ExchangeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExchangeType) Scan(value interface{}) error {
	if value == nil {
		ns.ExchangeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExchangeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExchangeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExchangeType), nil
}

type NakshatraType string

const (
	NakshatraTypeAshwini          NakshatraType = "Ashwini"
	NakshatraTypeBharani          NakshatraType = "Bharani"
	NakshatraTypeKrittika         NakshatraType = "Krittika"
	NakshatraTypeRohini           NakshatraType = "Rohini"
	NakshatraTypeMrigashirsha     NakshatraType = "Mrigashirsha"
	NakshatraTypeArdra            NakshatraType = "Ardra"
	NakshatraTypePunarvasu        NakshatraType = "Punarvasu"
	NakshatraTypePushya           NakshatraType = "Pushya"
	NakshatraTypeAshlesha         NakshatraType = "Ashlesha"
	NakshatraTypeMagha            NakshatraType = "Magha"
	NakshatraTypePurvaPhalguni    NakshatraType = "Purva Phalguni"
	NakshatraTypeUttaraPhalguni   NakshatraType = "Uttara Phalguni"
	NakshatraTypeHasta            NakshatraType = "Hasta"
	NakshatraTypeChitra           NakshatraType = "Chitra"
	NakshatraTypeSwati            NakshatraType = "Swati"
	NakshatraTypeVishakha         NakshatraType = "Vishakha"
	NakshatraTypeAnuradha         NakshatraType = "Anuradha"
	NakshatraTypeJyestha          NakshatraType = "Jyestha"
	NakshatraTypeMoola            NakshatraType = "Moola"
	NakshatraTypePurvaAshadha     NakshatraType = "Purva Ashadha"
	NakshatraTypeUttaraAshadha    NakshatraType = "Uttara Ashadha"
	NakshatraTypeAbhijit          NakshatraType = "Abhijit"
	NakshatraTypeShravana         NakshatraType = "Shravana"
	NakshatraTypeDhanishtha       NakshatraType = "Dhanishtha"
	NakshatraTypeShatabhisha      NakshatraType = "Shatabhisha"
	NakshatraTypePurvaBhadrapada  NakshatraType = "Purva Bhadrapada"
	NakshatraTypeUttaraBhadrapada NakshatraType = "Uttara Bhadrapada"
	NakshatraTypeRevati           NakshatraType = "Revati"
)

func (e *NakshatraType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NakshatraType(s)
	case string:
		*e = NakshatraType(s)
	default:
		return fmt.Errorf("unsupported scan type for NakshatraType: %T", src)
	}
	return nil
}

type NullNakshatraType struct {
	NakshatraType NakshatraType `json:"nakshatra_type"`
	Valid         bool          `json:"valid"` // Valid is true if NakshatraType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNakshatraType) Scan(value interface{}) error {
	if value == nil {
		ns.NakshatraType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NakshatraType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNakshatraType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NakshatraType), nil
}

type PlanetType string

const (
	PlanetTypeSun     PlanetType = "Sun"
	PlanetTypeMoon    PlanetType = "Moon"
	PlanetTypeMercury PlanetType = "Mercury"
	PlanetTypeVenus   PlanetType = "Venus"
	PlanetTypeMars    PlanetType = "Mars"
	PlanetTypeJupiter PlanetType = "Jupiter"
	PlanetTypeSaturn  PlanetType = "Saturn"
	PlanetTypeUranus  PlanetType = "Uranus"
	PlanetTypeNeptune PlanetType = "Neptune"
	PlanetTypePluto   PlanetType = "Pluto"
	PlanetTypeRahu    PlanetType = "Rahu"
	PlanetTypeKetu    PlanetType = "Ketu"
)

func (e *PlanetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanetType(s)
	case string:
		*e = PlanetType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanetType: %T", src)
	}
	return nil
}

type NullPlanetType struct {
	PlanetType PlanetType `json:"planet_type"`
	Valid      bool       `json:"valid"` // Valid is true if PlanetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanetType) Scan(value interface{}) error {
	if value == nil {
		ns.PlanetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanetType), nil
}

type RelType string

const (
	RelTypeFriend  RelType = "Friend"
	RelTypeNeutral RelType = "Neutral"
	RelTypeEnemy   RelType = "Enemy"
	RelTypeSelf    RelType = "Self"
)

func (e *RelType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RelType(s)
	case string:
		*e = RelType(s)
	default:
		return fmt.Errorf("unsupported scan type for RelType: %T", src)
	}
	return nil
}

type NullRelType struct {
	RelType RelType `json:"rel_type"`
	Valid   bool    `json:"valid"` // Valid is true if RelType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRelType) Scan(value interface{}) error {
	if value == nil {
		ns.RelType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RelType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRelType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RelType), nil
}

type SignType string

const (
	SignTypeAries       SignType = "Aries"
	SignTypeTaurus      SignType = "Taurus"
	SignTypeGemini      SignType = "Gemini"
	SignTypeCancer      SignType = "Cancer"
	SignTypeLeo         SignType = "Leo"
	SignTypeVirgo       SignType = "Virgo"
	SignTypeLibra       SignType = "Libra"
	SignTypeScorpio     SignType = "Scorpio"
	SignTypeSagittarius SignType = "Sagittarius"
	SignTypeCapricorn   SignType = "Capricorn"
	SignTypeAquarius    SignType = "Aquarius"
	SignTypePisces      SignType = "Pisces"
)

func (e *SignType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignType(s)
	case string:
		*e = SignType(s)
	default:
		return fmt.Errorf("unsupported scan type for SignType: %T", src)
	}
	return nil
}

type NullSignType struct {
	SignType SignType `json:"sign_type"`
	Valid    bool     `json:"valid"` // Valid is true if SignType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignType) Scan(value interface{}) error {
	if value == nil {
		ns.SignType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignType), nil
}

type SpeedType string

const (
	SpeedTypeKutil       SpeedType = "kutil"
	SpeedTypeAtiVakra    SpeedType = "ati-vakra"
	SpeedTypeVakra       SpeedType = "vakra"
	SpeedTypeAtiMand     SpeedType = "ati-mand"
	SpeedTypeMand        SpeedType = "mand"
	SpeedTypeMadhyam     SpeedType = "madhyam"
	SpeedTypeSama        SpeedType = "sama"
	SpeedTypeSheeghra    SpeedType = "sheeghra"
	SpeedTypeAtiSheeghra SpeedType = "ati-sheeghra"
	SpeedTypeNA          SpeedType = "n/a"
)

func (e *SpeedType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SpeedType(s)
	case string:
		*e = SpeedType(s)
	default:
		return fmt.Errorf("unsupported scan type for SpeedType: %T", src)
	}
	return nil
}

type NullSpeedType struct {
	SpeedType SpeedType `json:"speed_type"`
	Valid     bool      `json:"valid"` // Valid is true if SpeedType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpeedType) Scan(value interface{}) error {
	if value == nil {
		ns.SpeedType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SpeedType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpeedType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SpeedType), nil
}

type VedhaType string

const (
	VedhaTypeLeft  VedhaType = "left"
	VedhaTypeRight VedhaType = "right"
	VedhaTypeFront VedhaType = "front"
	VedhaTypeNo    VedhaType = "no"
	VedhaTypeNA    VedhaType = "n/a"
)

func (e *VedhaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VedhaType(s)
	case string:
		*e = VedhaType(s)
	default:
		return fmt.Errorf("unsupported scan type for VedhaType: %T", src)
	}
	return nil
}

type NullVedhaType struct {
	VedhaType VedhaType `json:"vedha_type"`
	Valid     bool      `json:"valid"` // Valid is true if VedhaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVedhaType) Scan(value interface{}) error {
	if value == nil {
		ns.VedhaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VedhaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVedhaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VedhaType), nil
}

type WeekDayType string

const (
	WeekDayTypeSunday    WeekDayType = "Sunday"
	WeekDayTypeMonday    WeekDayType = "Monday"
	WeekDayTypeTuesday   WeekDayType = "Tuesday"
	WeekDayTypeWednesday WeekDayType = "Wednesday"
	WeekDayTypeThursday  WeekDayType = "Thursday"
	WeekDayTypeFriday    WeekDayType = "Friday"
	WeekDayTypeSaturday  WeekDayType = "Saturday"
)

func (e *WeekDayType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WeekDayType(s)
	case string:
		*e = WeekDayType(s)
	default:
		return fmt.Errorf("unsupported scan type for WeekDayType: %T", src)
	}
	return nil
}

type NullWeekDayType struct {
	WeekDayType WeekDayType `json:"week_day_type"`
	Valid       bool        `json:"valid"` // Valid is true if WeekDayType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWeekDayType) Scan(value interface{}) error {
	if value == nil {
		ns.WeekDayType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WeekDayType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWeekDayType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WeekDayType), nil
}

type TblOhlc struct {
	Day      pgtype.Timestamptz `db:"day" json:"day"`
	TickerID int16              `db:"ticker_id" json:"ticker_id"`
	O        *float64           `db:"o" json:"o"`
	H        *float64           `db:"h" json:"h"`
	L        *float64           `db:"l" json:"l"`
	C        *float64           `db:"c" json:"c"`
	V        *float64           `db:"v" json:"v"`
}

type TblPanchang struct {
	Time      pgtype.Timestamptz `db:"time" json:"time"`
	Tithy     int16              `db:"tithy" json:"tithy"`
	Nakshatra NakshatraType      `db:"nakshatra" json:"nakshatra"`
	Weekday   WeekDayType        `db:"weekday" json:"weekday"`
}

type TblPlanetPosition struct {
	ObservationTime pgtype.Timestamptz `db:"observation_time" json:"observation_time"`
	PlanetName      PlanetType         `db:"planet_name" json:"planet_name"`
	Longitude       float64            `db:"longitude" json:"longitude"`
	Latitude        float64            `db:"latitude" json:"latitude"`
	Distance        float64            `db:"distance" json:"distance"`
	SpeedLong       float64            `db:"speed_long" json:"speed_long"`
	SpeedLat        float64            `db:"speed_lat" json:"speed_lat"`
	SpeedDist       float64            `db:"speed_dist" json:"speed_dist"`
	SpeedCategory   SpeedType          `db:"speed_category" json:"speed_category"`
	Vedha           VedhaType          `db:"vedha" json:"vedha"`
	Sign            *SignType          `db:"sign" json:"sign"`
	NakshatraName   *NakshatraType     `db:"nakshatra_name" json:"nakshatra_name"`
	NakshatraPada   *int16             `db:"nakshatra_pada" json:"nakshatra_pada"`
	IsRetro         *bool              `db:"is_retro" json:"is_retro"`
	SignLord        *PlanetType        `db:"sign_lord" json:"sign_lord"`
	SignLordship    *RelType           `db:"sign_lordship" json:"sign_lordship"`
	NavamsaSign     *SignType          `db:"navamsa_sign" json:"navamsa_sign"`
	Vargottama      *bool              `db:"vargottama" json:"vargottama"`
	UdayBala        *float64           `db:"uday_bala" json:"uday_bala"`
	UchchaBala      *float64           `db:"uchcha_bala" json:"uchcha_bala"`
	VakraBala       *float64           `db:"vakra_bala" json:"vakra_bala"`
	KshetraBala     *float64           `db:"kshetra_bala" json:"kshetra_bala"`
	NavamshaBala    *float64           `db:"navamsha_bala" json:"navamsha_bala"`
	LongitudeDms    []byte             `db:"longitude_dms" json:"longitude_dms"`
	LatitudeDms     []byte             `db:"latitude_dms" json:"latitude_dms"`
	SpeedLongDms    []byte             `db:"speed_long_dms" json:"speed_long_dms"`
}

type TblTicker struct {
	ID       int16        `db:"id" json:"id"`
	Name     string       `db:"name" json:"name"`
	Desc     *string      `db:"desc" json:"desc"`
	FullName *string      `db:"full_name" json:"full_name"`
	Exchange ExchangeType `db:"exchange" json:"exchange"`
}
