// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqls

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOLHC = `-- name: CreateOLHC :one
INSERT INTO tbl_ohlc (
  day, ticker_id, o, h, l, c, v
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING day, ticker_id, o, h, l, c, v
`

type CreateOLHCParams struct {
	Day      pgtype.Timestamptz `db:"day" json:"day"`
	TickerID int16              `db:"ticker_id" json:"ticker_id"`
	O        *float64           `db:"o" json:"o"`
	H        *float64           `db:"h" json:"h"`
	L        *float64           `db:"l" json:"l"`
	C        *float64           `db:"c" json:"c"`
	V        *float64           `db:"v" json:"v"`
}

func (q *Queries) CreateOLHC(ctx context.Context, arg CreateOLHCParams) (TblOhlc, error) {
	row := q.db.QueryRow(ctx, createOLHC,
		arg.Day,
		arg.TickerID,
		arg.O,
		arg.H,
		arg.L,
		arg.C,
		arg.V,
	)
	var i TblOhlc
	err := row.Scan(
		&i.Day,
		&i.TickerID,
		&i.O,
		&i.H,
		&i.L,
		&i.C,
		&i.V,
	)
	return i, err
}

const deleteOLHC = `-- name: DeleteOLHC :exec
DELETE FROM tbl_ohlc
WHERE day = $1 and ticker_id = $2
`

type DeleteOLHCParams struct {
	Day      pgtype.Timestamptz `db:"day" json:"day"`
	TickerID int16              `db:"ticker_id" json:"ticker_id"`
}

func (q *Queries) DeleteOLHC(ctx context.Context, arg DeleteOLHCParams) error {
	_, err := q.db.Exec(ctx, deleteOLHC, arg.Day, arg.TickerID)
	return err
}

const getOLHC = `-- name: GetOLHC :one
SELECT day, ticker_id, o, h, l, c, v FROM tbl_ohlc
WHERE day = $1 and ticker_id = $2 LIMIT 1
`

type GetOLHCParams struct {
	Day      pgtype.Timestamptz `db:"day" json:"day"`
	TickerID int16              `db:"ticker_id" json:"ticker_id"`
}

func (q *Queries) GetOLHC(ctx context.Context, arg GetOLHCParams) (TblOhlc, error) {
	row := q.db.QueryRow(ctx, getOLHC, arg.Day, arg.TickerID)
	var i TblOhlc
	err := row.Scan(
		&i.Day,
		&i.TickerID,
		&i.O,
		&i.H,
		&i.L,
		&i.C,
		&i.V,
	)
	return i, err
}

const listOLHCs = `-- name: ListOLHCs :many
SELECT day, ticker_id, o, h, l, c, v FROM tbl_ohlc
ORDER BY day
`

func (q *Queries) ListOLHCs(ctx context.Context) ([]TblOhlc, error) {
	rows, err := q.db.Query(ctx, listOLHCs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TblOhlc{}
	for rows.Next() {
		var i TblOhlc
		if err := rows.Scan(
			&i.Day,
			&i.TickerID,
			&i.O,
			&i.H,
			&i.L,
			&i.C,
			&i.V,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickers = `-- name: ListTickers :many
SELECT id, name, "desc", full_name, exchange
FROM tbl_ticker
ORDER BY name
`

func (q *Queries) ListTickers(ctx context.Context) ([]TblTicker, error) {
	rows, err := q.db.Query(ctx, listTickers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TblTicker{}
	for rows.Next() {
		var i TblTicker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Desc,
			&i.FullName,
			&i.Exchange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOLHC = `-- name: UpdateOLHC :exec
UPDATE tbl_ohlc
  set o = $3,
  h = $4,
  l = $5,
  c = $6,
  v = $7
WHERE day = $1 and ticker_id = $2
`

type UpdateOLHCParams struct {
	Day      pgtype.Timestamptz `db:"day" json:"day"`
	TickerID int16              `db:"ticker_id" json:"ticker_id"`
	O        *float64           `db:"o" json:"o"`
	H        *float64           `db:"h" json:"h"`
	L        *float64           `db:"l" json:"l"`
	C        *float64           `db:"c" json:"c"`
	V        *float64           `db:"v" json:"v"`
}

func (q *Queries) UpdateOLHC(ctx context.Context, arg UpdateOLHCParams) error {
	_, err := q.db.Exec(ctx, updateOLHC,
		arg.Day,
		arg.TickerID,
		arg.O,
		arg.H,
		arg.L,
		arg.C,
		arg.V,
	)
	return err
}

const upsertOLHC = `-- name: UpsertOLHC :execrows
INSERT INTO tbl_ohlc (
  day, ticker_id, o, h, l, c, v
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (day, ticker_id) DO UPDATE SET
  o = EXCLUDED.o,
  h = EXCLUDED.h,
  l = EXCLUDED.l,
  c = EXCLUDED.c,
  v = EXCLUDED.v
`

type UpsertOLHCParams struct {
	Day      pgtype.Timestamptz `db:"day" json:"day"`
	TickerID int16              `db:"ticker_id" json:"ticker_id"`
	O        *float64           `db:"o" json:"o"`
	H        *float64           `db:"h" json:"h"`
	L        *float64           `db:"l" json:"l"`
	C        *float64           `db:"c" json:"c"`
	V        *float64           `db:"v" json:"v"`
}

func (q *Queries) UpsertOLHC(ctx context.Context, arg UpsertOLHCParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertOLHC,
		arg.Day,
		arg.TickerID,
		arg.O,
		arg.H,
		arg.L,
		arg.C,
		arg.V,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
